name: Quality Assurance

on:
  push:
    branches:
      - main
  pull_request: ~

jobs:
  phpunit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          coverage: none
      - uses: ramsey/composer-install@v1
      - run: vendor/bin/phpunit
  psalm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          coverage: none
      - uses: ramsey/composer-install@v1
      - run: vendor/bin/psalm --output-format=github
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          coverage: none
      - uses: ramsey/composer-install@v1
      - run: vendor/bin/phpcs